- name: Make sure base directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,g=rx,o=rx'
  loop:
  - "{{ ood_base_apache_dir }}"
  - "{{ ood_app_dir }}"
  - "{{ ood_sys_app_dir }}"
  - "{{ ood_dev_app_dir }}"
  - "{{ ood_usr_app_dir }}"
  - "{{ ood_base_dir }}"
  - "{{ ood_base_apache_dir }}/public"
  - "{{ ood_base_apache_dir }}/discover"
  - "{{ ood_base_conf_dir }}"

- name: Make os directories when required
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 'u=rwx,g=rx,o=rx'
  loop: "{{ os_directories }}"
  when: os_directories is defined

# Have to remove these test directories because they don't copy well.  They have
# recursive symlinks that throw OSError: [Errno 40] Too many levels of symbolic links
- name: Rm findit2 test directory
  ansible.builtin.file:
    path: "{{ ood_source_dir }}/apps/files/{{ item }}"
    state: absent
  loop:
  - "node_modules/findit/test"
  - "lib/findit2/test"

- name: Move apps to their directories
  ansible.builtin.copy:
    src: "{{ ood_source_dir }}/apps/{{ item }}"
    dest: "{{ ood_sys_app_dir }}"
    owner: root
    group: root
    mode: 'u=rwX,g=rX,o=rX'
    remote_src: yes
  loop: "{{ ood_base_apps }}"

- name: Move core libs to their directories
  ansible.builtin.copy:
    src: "{{ ood_source_dir }}/{{ item }}"
    dest: "{{ ood_base_dir }}"
    owner: root
    group: root
    mode: 'u=rwX,g=rX,o=rX'
    remote_src: yes
  loop: "{{ ood_core_libs }}"

- name: Make nginx config files for core sys apps
  ansible.builtin.file:
    path: "{{ nginx_apps_dir }}/sys/{{ item }}.conf"
    state: touch
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  loop: "{{ ood_base_apps }}"

- name: Setup vendor bundle for dashboard
  ansible.builtin.command:
    cmd: "./bin/bundle config path --local vendor/bundle"
    chdir: "/var/www/ood/apps/sys/dashboard"

- name: Bundle install for dashboard
  ansible.builtin.command:
    cmd: "bundle install"
    chdir: "/var/www/ood/apps/sys/dashboard"

- name: Setup dashboard credentials
  copy:
    dest: "/var/www/ood/apps/sys/dashboard/config/credentials.yml.enc" 
    content: |
      1ETaGcR92AtdIgAl8qQ+W5RUPlPcxBZoVH3WH0olWnYwcFQZnrTXrVwIKKRbADJpIbZy2pEkmF9HYdzi+GCvG7lRVtjQ+MjVyJtsn/VlwS8BZZ2YDPFz1qLVncJnPYynVb4xTU9WgCqTr+a9vH+XaPAZF0iqI6UoI6yOaybWY+xnd0aDoK3hf2q3zRUOiaCaifQlxjxkobno+LZRUTypnA6mKKf2Rox9V894StSGO/3aEDORglKfTYNPnx5vkLkeunlKOnYCGHkvd6490h1tK4OBoKhOqZ7UUBw0qM/0T/Jy4rJahcPr4PsxV5SulsdRirXSXsGfEUZRdKbSCIT+MLrV+Ugta6UTWxWXMQAF+BYvMYR3wfDXw6s8VYxMIAg962tf3AiXDLLJdAbayNXTN7eqDAyF/pWeaZC7--7JLRMdWRnU8tWyPI--FBK1iaidARrlA24mpb/g9Q==
  copy:
    dest: "/var/www/ood/apps/sys/dashboard/config/master.key"
    content: |
        7d0a0b725d801aa94b3c76b7c60221fd
  
- name: Build dashboard
  ansible.builtin.command: 
    cmd: "./bin/setup"
    chdir: "/var/www/ood/apps/sys/dashboard"
  environment:
    RAILS_ENV: production
    SECRET_KEY_BASE: 460cdca8753de6444a2b4d3be5eddb0325060549630503537f5fde8981801a489248631dff133011ff0eaf66d4d3620ca00785e57110254d258144a42f6a093e

#- name: Re-compile dashboard javascript
#  ansible.builtin.command: 
#    cmd: "./bin/recompile_js"
#    chdir: "/var/www/ood/apps/sys/dashboard"

- name: Make version file
  ansible.builtin.copy:
    content: "{{ ood_source_version }}"
    dest: "{{ ood_base_dir }}/VERSION"
    mode: 'u=rw,g=r,o=r'

- name: Cleanup build logfiles
  ansible.builtin.file:
    path: "{{ ood_sys_app_dir }}/log/production.log"
    state: absent
  loop: "{{ ood_base_apps }}"

- name: Give the apache user rights to nginx_stage
  ansible.builtin.template:
    src: ood-sudoers.j2
    dest: /etc/sudoers.d/ood
    mode: 'u=rw,g=,o='
